security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                default_target_path: app_login
            logout:
                path: app_logout
                target: app_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMINISTRATEUR }
        - { path: ^/medecin, roles: ROLE_MEDECIN }
        - { path: ^/patient, roles: ROLE_PATIENT }
        - { path: ^/pharmacien, roles: ROLE_PHARMACIEN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/ordonnance/my, roles: ROLE_PATIENT }
        - { path: ^/patient/dashboard, roles: ROLE_PATIENT }
        - { path: ^/pharmacien/dashboard, roles: ROLE_PHARMACIEN }
        - { path: ^/pharmacien/ordonnances, roles: ROLE_PHARMACIEN }
        - { path: ^/pharmacien/validate, roles: ROLE_PHARMACIEN }
        - { path: ^/pharmacien/medicaments, roles: ROLE_PHARMACIEN }
        - { path: ^/pharmacien/medicament/add, roles: ROLE_PHARMACIEN }
        - { path: ^/pharmacien/medicament/update, roles: ROLE_PHARMACIEN }
        - { path: ^/pharmacien/medicament/delete, roles: ROLE_PHARMACIEN }